### ISSUE TITLE
As a user, I would like to have flash cards read to me.

### ISSUE THREAD

**Issue by iamdarkes** [cs480SnackOverflow/front-end#7]

**Comment by baoqchau** [comment]
@jdarkes how are u doing on this one Victor? just want to check in

**Comment by 84danie** [comment]
According to this guide, https://medium.com/@anaptfox/getting-started-with-amazon-polly-using-node-js-345e84dbd23d, we should be able to implement Amazon Poly on the frontend. @baoqchau please doublecheck this.
